### ISSUE TITLE
LP5521YQ need to change to fit KLC

### ISSUE THREAD

**Issue by jeromebeguin** [jeromebeguin/G-KiCad-Lib#5]
@GrafAnto 
Changes have to be mande on LP5521YQ in order to fit the KLC rules.
- Power pin on top
- Pins aligned with 100mil grid
- Out border 10mil thick
- Add description, key work and web link to datasheet
Check KLC section 4.

**Comment by GrafAnto** [comment]
LP5521YQ Updated to fit KLC
